export const ICONS={
 new:'M5 2h8l5 5v15H5z M13 2v6h5 M8 14h7 M11.5 10.5v7',folder:'M2 6h7l2 2h11l-3 12H2z M2 6V4h7l2 2h9v2',save:'M3 3h15l3 3v15H3z M7 3v6h9V3 M7 21v-8h10v8',undo:'M8 6L3 11l5 5 M3 11h11a6 6 0 0 1 6 6',redo:'M16 6l5 5-5 5 M21 11H10a6 6 0 0 0-6 6',search:'M16 16l5 5 M18 10a8 8 0 1 1-16 0 8 8 0 0 1 16 0',sun:'M12 3v-2 M12 23v-2 M3 12H1 M23 12h-2 M4 4l2 2 M18 18l2 2 M4 20l2-2 M18 6l2-2 M17 12a5 5 0 1 1-10 0 5 5 0 0 1 10 0',sidebar:'M3 3h18v18H3z M9 3v18 M5.5 7h1 M5.5 11h1', 'sidebar-right':'M3 3h18v18H3z M15 3v18 M17 7h1 M17 11h1',run:'M7 3l14 9-14 9z',runall:'M4 3l10 9L4 21z M14 3l7 9-7 9',stop:'M5 5h14v14H5z',copy:'M8 8h13v13H8z M4 16H2V2h14v2',paste:'M8 5H4v17h16V5h-4 M8 2h8v6H8z',cut:'M9 9l11 11 M9 15L20 3 M9 7a3 3 0 1 1-6 0 3 3 0 0 1 6 0 M9 17a3 3 0 1 1-6 0 3 3 0 0 1 6 0',code:'M8 5l-6 7 6 7 M16 5l6 7-6 7 M14 2l-4 20',text:'M3 4h18 M12 4v17 M7 21h10',heading:'M5 3v18 M19 3v18 M5 12h14',plot:'M3 2v19h19 M5 15c3-15 8 11 14-8',surface:'M2 9l10-6 10 6v7l-10 6-10-6z M2 9l10 6 10-6 M12 15v7 M7 6l10 6 M7 12l10-6',matrix:'M7 2H3v20h4 M17 2h4v20h-4 M8 7h1 M15 7h1 M8 12h1 M15 12h1 M8 17h1 M15 17h1',export:'M4 14v7h16v-7 M12 2v13 M7 7l5-5 5 5',print:'M6 7V2h12v5 M6 17H2V8h20v9h-4 M6 13h12v9H6z M17 11h1',sheet:'M5 2h9l5 5v15H5z M14 2v6h5 M8 12h8 M8 16h8',refresh:'M21 10a9 9 0 1 0-2 8 M21 3v7h-7',help:'M9 8a3 3 0 1 1 4 3v3 M12 18h.01 M22 12a10 10 0 1 1-20 0 10 10 0 0 1 20 0',chevron:'M6 9l6 6 6-6'};
export const icon=name=>`<svg viewBox="0 0 24 24" aria-hidden="true"><path d="${ICONS[name]||ICONS.sheet}"/></svg>`;
export const PALETTES=[
 {title:'Expressions',open:true,items:[['<span class="fraction"><span>a</span><span>b</span></span>','(□)/(x)','Fraction'],['x<sup>2</sup>','(□)^2','Square'],['x<sup>n</sup>','(□)^n','Power'],['√x','sqrt(□)','Square root'],['|x|','abs(□)','Absolute value'],['e<sup>x</sup>','exp(□)','Exponential'],['ln','ln(□)','Natural logarithm'],['x!','factorial(□)','Factorial'],['( )','(□)','Parentheses'],['[ ]','[□, 2, 3]','List'],['x ≔','f := □','Assignment'],['x ↦','f := x -> □','Function definition']]},
 {title:'Calculus',open:true,items:[['<span class="fraction"><span>d</span><span>dx</span></span>','diff(□, x)','Derivative'],['∂','diff(□, y)','Partial derivative'],['∫','int(□, x)','Indefinite integral'],['∫<sub>a</sub><sup>b</sup>','int(□, x=0..1)','Definite integral'],['lim','limit(□, x=0)','Limit'],['Σ','sum(□, k=1..10)','Finite sum'],['Π','product(□, k=1..5)','Finite product'],['∑<small>∞</small>','series(□, x=0, 6)','Taylor series']]},
 {title:'Greek letters',open:true,items:[['α','alpha','Alpha'],['β','beta','Beta'],['γ','gamma','Gamma'],['δ','delta','Delta'],['θ','theta','Theta'],['λ','lambda','Lambda'],['μ','mu','Mu'],['π','Pi','Pi'],['σ','sigma','Sigma'],['φ','phi','Phi'],['ψ','psi','Psi'],['ω','omega','Omega']]},
 {title:'Linear algebra',open:false,items:[['▦','@matrix','Matrix builder'],['det','det(□)','Determinant'],['A<sup>−1</sup>','inverse(□)','Inverse'],['A<sup>T</sup>','transpose(□)','Transpose'],['tr','trace(□)','Trace'],['rank','rank(□)','Rank'],['rref','rref(□)','Reduced row-echelon form'],['→','Vector([□, 2, 3])','Column vector']]},
 {title:'Functions & constants',open:false,items:[['sin','sin(□)','Sine'],['cos','cos(□)','Cosine'],['tan','tan(□)','Tangent'],['e','e','Euler number'],['asin','asin(□)','Inverse sine'],['cosh','cosh(□)','Hyperbolic cosine'],['π','Pi','Pi constant'],['i','I','Imaginary unit']]}
];
export const COMMANDS=[
 ['Simplify an expression','simplify(sin(x)^2 + cos(x)^2)','Algebra'],['Expand a polynomial','expand((x + 1)^5)','Algebra'],['Factor a polynomial','factor(x^3 - 6*x^2 + 11*x - 6)','Algebra'],['Solve an equation','solve(x^2 - 5*x + 6 = 0, x)','Equations'],['Solve a linear system','solve([2*x+y=5, x-y=1], [x,y])','Equations'],['Find real roots in an interval','fsolve(cos(x)-x, x=0..2)','Numerics'],['Differentiate','diff(sin(x)*exp(x), x)','Calculus'],['Second derivative','diff(exp(-x^2), x, 2)','Calculus'],['Integrate symbolically','int(x^2 + sin(x), x)','Calculus'],['Definite integral','int(x^2, x=0..1)','Calculus'],['Numerical quadrature','int(exp(-x^2), x=0..1)','Numerics'],['Evaluate a limit','limit(sin(x)/x, x=0)','Calculus'],['Taylor polynomial','series(exp(x), x=0, 7)','Calculus'],['Finite summation','sum(k^2, k=1..100)','Discrete math'],['Finite product','product(k, k=1..10)','Discrete math'],['Substitute a value','subs(x=2, x^3+3*x+1)','Evaluation'],['Numerical value','evalf(Pi^2/6)','Evaluation'],['Define a function','f := x -> exp(-x^2)','Definitions'],['Create a matrix','A := Matrix([[2,1,0],[1,3,1],[0,1,2]])','Linear algebra'],['Matrix inverse','inverse(Matrix([[2,1],[1,3]]))','Linear algebra'],['Matrix determinant','det(Matrix([[2,1],[1,3]]))','Linear algebra'],['Row reduction','rref(Matrix([[1,2,3],[4,5,6]]))','Linear algebra'],['Plot functions','plot([sin(a*x), cos(x)], x=-6..6)','Visualization'],['Plot a 3D surface','plot3d(sin(a*x)*cos(y), x=-5..5, y=-5..5)','Visualization'],['Solve an initial-value ODE','ode(-0.3*y + sin(t), y=1, t=0..20)','Numerics'],['Sample standard deviation','stdev([2,4,4,4,5,5,7,9])','Statistics'],['Arithmetic mean','mean([1,2,3,4,5])','Statistics'],['Median','median([8,2,6,4,10])','Statistics']
];
export const EXAMPLES=[
 {key:'symbolic',title:'Symbolic exploration',subtitle:'Exact answers. Clear thinking. A worksheet for exploring the connections in mathematics.',icon:'ƒ',description:'Factor, differentiate, and bring a parameterized function to life.',cells:[['heading','Algebra & calculus'],['code','factor(x^3 - 6*x^2 + 11*x - 6);'],['code','diff(exp(-x^2), x);'],['heading','A function, brought to life'],['code','plot([exp(-x^2/12)*sin(2*a*x), exp(-x^2/12)], x=-6..6);'],['text','Move the slider to vary a. Drag the plot to pan, scroll to zoom, and hover over a curve to inspect its value.'],['heading','Exact, all the way down'],['code','int(x^2, x=0..1);'],['code','limit(sin(x)/x, x=0);']]},
 {key:'linear',title:'Linear algebra',subtitle:'Work with exact matrices, solve systems, and inspect every result.',icon:'▦',description:'Matrix arithmetic, determinants, inverses, and exact linear systems.',cells:[['heading','Define a symmetric matrix'],['code','A := Matrix([[2,1,0], [1,3,1], [0,1,2]]);'],['code','det(A);'],['heading','Invert & verify'],['code','inverse(A);'],['code','A*inverse(A);'],['heading','Solve a linear system'],['code','solve([2*x+y=5, x-y=1], [x,y]);']]},
 {key:'surface',title:'Surface studio',subtitle:'Explore the geometry of a function with a real, interactive 3D rendering pipeline.',icon:'◈',description:'An orbitable surface, live parameters, wireframe, and GPU shading.',cells:[['heading','The geometry of oscillation'],['code','plot3d(sin(a*x)*cos(y)*exp(-(x^2+y^2)/18), x=-5..5, y=-5..5);'],['text','Drag to orbit, hold Shift to pan, or scroll to zoom. Toggle the wireframe or start automatic rotation from the plot toolbar.'],['heading','A partial derivative'],['code','diff(sin(x)*cos(y)*exp(-(x^2+y^2)/18), x);']]},
 {key:'calculus',title:'Calculus notebook',subtitle:'Differentiate, integrate, and examine local behavior with exact symbolic operations.',icon:'∫',description:'Chain rules, integration, limits, and Taylor polynomials.',cells:[['heading','Differentiate a composition'],['code','diff(sin(x^2)*exp(x), x);'],['heading','Integration by parts'],['code','int(x*exp(x), x);'],['code','int(exp(-x^2), x=0..1);'],['heading','Taylor polynomial'],['code','series(sin(x), x=0, 8);'],['code','limit((1-cos(x))/x^2, x=0);'],['heading','Compare a series with the function'],['code','plot([sin(x), x-x^3/6+x^5/120], x=-4..4);']]},
 {key:'dynamics',title:'Dynamics & numerics',subtitle:'An explicit scalar initial-value problem, integrated locally with fourth-order Runge–Kutta.',icon:'ẏ',description:'Real numerical ODE integration, root finding, and quadrature.',cells:[['heading','Forced, damped response'],['text','Solve dy/dt = −0.3y + sin(t), with y(0) = 1. This is a fixed-step, non-stiff, scalar IVP solver, not a general symbolic ODE solver.'],['code','ode(-0.3*y + sin(t), y=1, t=0..30);'],['heading','Find an equilibrium numerically'],['code','fsolve(cos(x)-x, x=0..2);'],['heading','Numerical quadrature'],['code','int(exp(-x^2), x=0..1);']]},
 {key:'blank',title:'Untitled worksheet',subtitle:'A new idea starts here.',icon:'＋',description:'A clean page, an exact kernel, and room to think.',cells:[['code','']]}
];
